language: c

sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_aptget libglpk-dev
  - ./travis-tool.sh install_github statnet/EpiModel jimhester/covr
  - ./travis-tool.sh r_binary_install httpuv
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - global:
      - R_BUILD_ARGS=--no-manual
      - R_CHECK_ARGS=--as-cran
      - BOOTSTRAP_LATEX=1
      - WARNINGS_ARE_ERRORS=1
      - _R_CHECK_FORCE_SUGGESTS_=0
      - NOT_CRAN=true
